server:
  port: 8090
  forward-headers-strategy: native
  compression:
    enabled: false
    mime-types: application/javascript,text/css,application/json,application/xml,text/html,text/xml,text/plain
  servlet:
    application-display-name: Aamir Application
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  #  devtools:
  #    add-properties: false
  output:
    ansi:
      enabled: always
  datasource:
    type: com.zaxxer.hikari.HikariDataSource

    # H2 Database 配置
    #    driver-class-name: org.h2.Driver
    #    url: jdbc:h2:file:~/.Aamir/db/Aamir
    #    username: admin
    #    password: 123456

    #     MySQL 配置
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/aamir?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: root

  h2:
    console:
      settings:
        web-allow-others: false
      path: /h2-console
      enabled: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true


  flyway:
    enabled: false
  servlet:
    multipart:
      max-file-size: 10240MB
      max-request-size: 10240MB
  freemarker:
    template-loader-path: classpath:/templates
    suffix: .ftl
  mvc:
    static-path-pattern: /static/**
#  thymeleaf:
#    prefix: classpath:/templates/
#  mvc:
#    static-path-pattern: /static/X-admin/**


#  mail:
#    host: smtp.qq.com
#    username: 229047180@qq.com
#    password: ysnoctwpglyybiai
#    default-encoding: UTF-8



#management:
#  endpoints:
#    web:
#      base-path: /actuator
#      exposure:
#        include: ['httptrace', 'metrics','env','logfile','health']
logging:
  level:
    Aamir: INFO
  file:
    path: ${user.home}/.Aamir/logs

##jwt配置
audience:
  # 代表这个JWT的接收对象,存入audience
  clientId: 098f6bcd4621d373cade4e832627b4f6
  # 密钥, 经过Base64加密, 可自行替换
  base64Secret: MDk4ZjZiY2Q0NjIxZDM3M2NhZGU0ZTgzMjYyN2I0ZjY=
  # JWT的签发主体，存入issuer
  name: restapiuser
  # 过期时间，时间戳
  expiresSecond: 172800







author:
  name:peiyunluo
  email:peiyunluo@icloud.com
Aamir:
  name:Aamir
  description:presonal blog
  version:v0.0.1

#  本次毕业设计实现一个个人的博客系统。该系统主要的核心功能包括：
#  1 对于管理员（博客主），提供仪表盘，主要是包括新的动态，文章数量，评论数量，
#  访问数量等信息的展示与管理；以及文章的管理；页面的管理，评论的管理，博客展示的管理，
#  个人资料的管理，及其文章备份，markdown文章的导入。
#  2 对于游客可以查看文章，查看评论，参与评论。